apiVersion: v1
metadata:
  name: health-secret
data:
  auth: {{ required "please set a password to secure the health endpoint" (htpasswd .Values.ingress.health.user .Values.ingress.health.password) | b64enc }}
  
kind: Secret
type: Opaque