{{- if .Values.ingress.enabled -}}
{{- $fullName := include "chart.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hub-health
  labels:
    {{- if .Values.ingress.gardenerCertManager }}
    garden.sapcloud.io/purpose: managed-cert
    {{- end }}
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.health.annotations | nindent 4 }}
    {{- if .Values.ingress.gardenerDNS }}
    dns.gardener.cloud/class: garden
    dns.gardener.cloud/dnsnames: {{ .Values.ingress.host }}
    {{- end }}
spec:
  {{- if .Values.ingress.tlsEnabled }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.tlsSecret }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      {{- range .Values.ingress.health.paths }}
        - path: {{ .path }}
          pathType: ImplementationSpecific
          backend:
            service:
              name: {{ $fullName }}
              port:
                number: {{ .servicePort }}
      {{- end }}
{{- end }}
