---
# secretCluster secret:
apiVersion: v1
data:
  kubeconfig: {{ required ".Values.secretConfig.secretCluster is required" .Values.secretConfig.secretCluster | b64enc }}
kind: Secret
metadata:
  name: secret-cluster-kubeconfig
  labels:
    {{- include "chart.labels" . | nindent 4 }}
---
# apprepo secret:
# note: key apprepokubeconfig is the name of the file where the secret is mounted. Do not change!
apiVersion: v1
kind: Secret
data:
  apprepokubeconfig: {{ required ".Values.secretConfig.apprepoCluster is required" .Values.secretConfig.apprepoCluster | b64enc }}
metadata:
  name: apprepo-cluster-kubeconfig
  labels:
    {{- include "chart.labels" . | nindent 4 }}
---
# hubsec imagepullsecret
{{- if .Values.secretConfig.hubImagePullSecret }}
apiVersion: v1
kind: Secret
data:
  hub: {{ .Values.secretConfig.hubImagePullSecret | b64enc }}
metadata:
  name: hubsec-image-pull-secrets-creds
  labels:
    {{- include "chart.labels" . | nindent 4 }}
{{- end }}
---
# secret for private keys
apiVersion: v1
data:
  secretDeletionKey: {{ .Values.secretConfig.secretDeletionKey | b64enc }}
kind: Secret
metadata:
  name: secret-private-keys
  labels:
  {{- include "chart.labels" . | nindent 4 }}