apiVersion: kubeapps.com/v1alpha1
kind: AppRepository
metadata:
  labels:
    app: hub-kubeapps-internal-apprepository-controller
    chart: kubeapps-0.12.0-dev
    heritage: Helm
    release: hub
  name: incubator
  namespace: default
  resourceVersion: "11043890"
  selfLink: /apis/kubeapps.com/v1alpha1/namespaces/hub/apprepositories/incubator
  uid: 90a893d4-d795-4daf-a3ab-9eb27abb4ecf
spec:
  syncJobPodTemplate:
    spec:
      imagePullSecrets:
      - name: artifactory
  type: helm
  url: https://kubernetes-charts-incubator.storage.googleapis.com
