# permissions to do viewer clusterboms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterbom-viewer-role
rules:
- apiGroups:
  - hub.k8s.sap.com
  resources:
  - clusterboms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hub.k8s.sap.com
  resources:
  - clusterboms/status
  verbs:
  - get
