apiVersion: "hub.k8s.sap.com/v1"
kind: ClusterBom
metadata:
  name: fs-test
  namespace: garden-hubtest
  labels:
    hub.k8s.sap.com/cluster-name: clusterA
spec:
  secretRef: fs-test.kubeconfig

  applicationConfigs:
  - id: ecm
    configType: helm
    values:
      nodes: 5
      multidc: false
    typeSpecificData:
      installName: "service-catalog"
      namespace: "ecm"
      catalogAccess:
        chartName: "docscv-java"
        repo: "stable"
        chartVersion: "0.2.5"
  - id: ecmmongo
    configType: helm
    values:
      replicaset: true
      nodes: 1
    typeSpecificData:
      installName: "mongo"
      namespace: "mongo"
      tarballAccess:
        chartUrl: "https://kubernetes-charts-incubator.storage.googleapis.com/mongodb-0.1.1.tgz"
        authHeader: "Affe"
