apiVersion: hub.k8s.sap.com/v1
kind: ClusterBom
metadata:
  name: cluster1bom
spec:

  secretRef: abD-kubeconfig

  applicationConfigs:
    - id: id1
      configType: helm

      typeSpecificData:
        installName: "test"
        namespace: ttt1s
        catalogAccess:
          chartName: dfdf
          chartVersion: 1.2.3
          repo: sdds
        #tarballAccess:
          #url: ffft
    - id: id2
      configType: helm

      typeSpecificData:
        installName: "test"
        namespace: ttt1s
        catalogAccess:
          chartName: fgfg
          chartVersion: 1.2.3
          repo: sdds
          #tarballAccess:
          #url: ffft


