apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hub.sapcloud.io:project-member:clusterbom-role
  labels:
    rbac.gardener.cloud/aggregate-to-project-member: "true"
rules:
  - apiGroups:
      - hub.k8s.sap.com
    resources:
      - clusterboms
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch

  - apiGroups:
      - hub.k8s.sap.com
    resources:
      - clusterbomsyncs
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - kappctrl.k14s.io
    resources:
      - apps
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - landscaper.gardener.cloud
    resources:
      - dataobjects
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - landscaper.gardener.cloud
    resources:
      - deployitems
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - landscaper.gardener.cloud
    resources:
      - executions
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - landscaper.gardener.cloud
    resources:
      - installations
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - landscaper.gardener.cloud
    resources:
      - targets
    verbs:
      - get
      - list
      - watch
