apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: apprepository-reader
  namespace: hub
rules:
- apiGroups:
  - "kubeapps.com"
  resources:
  - apprepositories
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: apprepository-controller-rolebinding
  namespace: hub
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: apprepository-reader
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: system:serviceaccount:hub:apprepository-reader
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: system:serviceaccount:hub:apprepository-reader2

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: apprepository-reader
  namespace: hub

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: apprepository-reader2
  namespace: hub
